[package]
name = "raven"
version = "0.1.0"
authors = ["Roey Darwish Dror <roeyd@infinidat.com>"]

[dependencies]
regex = "*"
time = "*"
uuid = "*"
rustc-serialize = "*"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper.git"
